#!/bin/bash
# VibeOS session-start status — wired as a SessionStart hook in .claude/settings.json
# (generated by scripts/setup_machine.sh). Prints a short status into the session so
# nothing depends on you remembering. Cheap by design: reads two small files, no scans.

cd "$(dirname "$0")/../.." || exit 0   # workspace root
QUEUE="0. vibeos-global/global cognitive layer/review_queue.md"

python3 - "$QUEUE" <<'PY'
import re, sys
from pathlib import Path

queue = Path(sys.argv[1])
lines = ["[VibeOS] First, read '0. vibeos-global/SOUL.md' and your USER.md so your team knows who it's working for."]

# Count items awaiting your judgment in the review queue's Pending section.
if queue.exists():
    text = queue.read_text(encoding="utf-8")
    pending_block = text.split("## Pending", 1)[-1].split("## Resolved", 1)[0]
    pending = len(re.findall(r"^### ", pending_block, flags=re.M))
    if pending:
        lines.append(f"[VibeOS] Review queue: {pending} item(s) waiting on your call — run /vcos-review when you have a moment.")
    else:
        lines.append("[VibeOS] Review queue: nothing pending.")

lines.append("[VibeOS] End a working session with /vcos-session-close so the team's memory keeps up.")
print("\n".join(lines))
PY
